### ISSUE TITLE
[events] Start work on the event page for excalibur

### ISSUE THREAD

**Issue by techsavvyash** [technobyte-nitkkr/Spardha#34]

**Comment by Debatreya** [comment]
## Assign this to me
please verify this design
![Screenshot (31)](https://github.com/technobyte-nitkkr/Spardha/assets/116421305/c0ea5b38-3395-4e40-9adf-236e68c492d2)
 and assign

**Comment by techsavvyash** [comment]
Huge shoutout to @Debatreya for closing this our single handedly!!🔥
