### ISSUE TITLE
bugs/improvements

### ISSUE THREAD

**Issue by techsavvyash** [technobyte-nitkkr/Spardha#46]
- [x] Popup
- [x] footer @Moddynow69 
- [x] about 
- [x] teams 
- [ ] 3d model
- [x] responsiveness:
   - [x] sponsor 
   - [x] guest
- [x] Guest lecture (as set of 3 cards)
- [x] Contacts us (sponsor)
- [x] Login (deprioritised)

**Comment by Saanvi26** [comment]
About section - #51

**Comment by Moddynow69** [comment]
> * [ ]  Popup
> * [x]  footer @Moddynow69
> * [ ]  about
> * [ ]  teams
> * [ ]  3d model
> * [ ]  responsiveness:
>   
>   * [ ]  sponsor
>   * [ ]  guest
> * [ ]  Guest lecture (as set of 3 cards)
> * [ ]  Contacts us (sponsor)
> * [ ]  Login (deprioritised)
